annual

diff --git a/.github/workflows/CI-CD_admin.yaml b/.github/workflows/CI-CD_admin.yaml
--- a/.github/workflows/CI-CD_admin.yaml
+++ b/.github/workflows/CI-CD_admin.yaml
@@ -7,7 +7,9 @@ on:
 #   pull_request:
 #     branches:
 #       - main
-
+permissions:
+  contents: write
+  
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -45,7 +47,7 @@ jobs:
       - name: Update Kubernetes deployment with new image tag
         run: |
           sed -i "s|image: expotechx/admin:.*|image: expotechx/admin:${{ env.COMMIT_HASH }}|" k8s/admin-app.yaml
-          
+          cat k8s/admin-app.yaml
 
       - name: Configure Git Credentials
         run: |
@@ -82,9 +84,11 @@ jobs:
         mkdir -p ~/.kube
         echo "$KUBECONFIG_FILE" > ~/.kube/config
         chmod 600 ~/.kube/config
+        kubectl config view || (echo "Invalid kubeconfig" && exit 1)
 
-    - name: Verify Kubernetes Connection
-      run: |
-        kubectl config view
-        kubectl -n admin apply -f k8s/admin-app.yaml
-        kubectl -n admin get pods
+    - name: Validate Kubernetes Manifest
+      run: kubectl -n admin apply -f k8s/admin-app.yaml --dry-run=client
+    - name: Apply Kubernetes Manifest
+      run: kubectl -n admin apply -f k8s/admin-app.yaml
+    - name: Verify Pods
+      run: kubectl -n admin get pods
